import MySQLdb
print('Conectando...')
conn = MySQLdb.connect(user='root', passwd='admin', host='127.0.0.1', port=3306, charset='utf8')

criar_tabelas = '''-- MySQL Script generated by MySQL Workbench
-- Tue Dec  7 20:40:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mylista
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mylista
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mylista` DEFAULT CHARACTER SET utf8 ;
USE `mylista` ;

-- -----------------------------------------------------
-- Table `mylista`.`STUDIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mylista`.`STUDIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mylista`.`GENERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mylista`.`GENERO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mylista`.`SERIE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mylista`.`SERIE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(60) NOT NULL,
  `EPS` INT NOT NULL,
  `TEMPS` VARCHAR(45) NOT NULL,
  `SINOPSE` LONGTEXT NOT NULL,
  `NOTA` REAL NOT NULL,
  `STUDIO_ID` INT NOT NULL,
  `GENERO_ID` INT NOT NULL,
  `ANO` INT NOT NULL,
  PRIMARY KEY (`ID`, `STUDIO_ID`, `GENERO_ID`),
  INDEX `fk_SERIE_STUDIO_idx` (`STUDIO_ID` ASC) VISIBLE,
  INDEX `fk_SERIE_GENERO1_idx` (`GENERO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_SERIE_STUDIO`
    FOREIGN KEY (`STUDIO_ID`)
    REFERENCES `mylista`.`STUDIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SERIE_GENERO1`
    FOREIGN KEY (`GENERO_ID`)
    REFERENCES `mylista`.`GENERO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mylista`.`MOVIE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mylista`.`MOVIE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(60) NOT NULL,
  `DURATION` VARCHAR(10) NOT NULL,
  `SINOPSE` LONGTEXT NOT NULL,
  `NOTA` REAL NOT NULL,
  `STUDIO_ID` INT NOT NULL,
  `GENERO_ID` INT NOT NULL,
  `ANO` INT NOT NULL,
  PRIMARY KEY (`ID`, `STUDIO_ID`, `GENERO_ID`),
  INDEX `fk_MOVIE_STUDIO1_idx` (`STUDIO_ID` ASC) VISIBLE,
  INDEX `fk_MOVIE_GENERO1_idx` (`GENERO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_MOVIE_STUDIO1`
    FOREIGN KEY (`STUDIO_ID`)
    REFERENCES `mylista`.`STUDIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MOVIE_GENERO1`
    FOREIGN KEY (`GENERO_ID`)
    REFERENCES `mylista`.`GENERO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mylista`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mylista`.`USUARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `SENHA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mylista`.`MINHA_LISTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mylista`.`MINHA_LISTA` (
  `USUARIO_ID` INT NOT NULL,
  `MOVIE_ID` INT NOT NULL,
  `SERIE_ID` INT NOT NULL,
  PRIMARY KEY (`USUARIO_ID`, `MOVIE_ID`, `SERIE_ID`),
  INDEX `fk_USUARIO_has_MOVIE_MOVIE1_idx` (`MOVIE_ID` ASC) VISIBLE,
  INDEX `fk_USUARIO_has_MOVIE_USUARIO1_idx` (`USUARIO_ID` ASC) VISIBLE,
  INDEX `fk__SERIE1_idx` (`SERIE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_has_MOVIE_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `mylista`.`USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_has_MOVIE_MOVIE1`
    FOREIGN KEY (`MOVIE_ID`)
    REFERENCES `mylista`.`MOVIE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk__SERIE1`
    FOREIGN KEY (`SERIE_ID`)
    REFERENCES `mylista`.`SERIE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
'''


conn.commit()
cursor.close()
